import {clubDirectory} from './clubs.mjs';
import {campusDetails} from './campus.mjs';
import {parseMedia} from './public/watch-model.js';
import {calendarEvent} from './calendar.mjs';
import {campusDateParts} from './public/event-utils.js';
import QRCode from 'qrcode';

export function createCommunity({db,get,all,run,id,now,fail,string,campusAccount,campusAccess,body,json,sockets,send,validSocket,watch,posters}){
 const person=userId=>get("SELECT id,name,username,avatarId FROM users WHERE id=? AND passwordHash<>'!disabled'",userId);
 const peer=(userId,u)=>get("SELECT id,name,username,avatarId FROM users WHERE id=? AND universityId=? AND passwordHash<>'!disabled'",userId,u.universityId)||fail(404,'Student not found on your campus');
 const text=(value,max,label)=>{const v=string(value,max,label);if(!v)fail(400,'Enter '+label.toLowerCase());return v;};
 const integer=(value,min,max,label)=>{if(!Number.isInteger(value)||value<min||value>max)fail(400,`${label} must be between ${min} and ${max}`);return value;};
 const future=value=>{if(typeof value!=='string'||!Number.isFinite(Date.parse(value))||Date.parse(value)<=Date.now()||Date.parse(value)>Date.now()+366*86400000)fail(400,'Choose a future date within one year');return new Date(value).toISOString();};
 const transaction=fn=>{db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}};
 function emit(userId,type='community:changed',data={}){for(const ws of sockets)if(ws.social&&ws.user.id===userId){if(!validSocket(ws))ws.close(4001,'Session expired');else send(ws,type,data);}}
 function notify(userId,kind,title,href,dedupe){if(!person(userId))return;const result=run('INSERT OR IGNORE INTO notifications (id,userId,kind,title,href,dedupe,createdAt) VALUES (?,?,?,?,?,?,?)',id(),userId,kind,title,href,dedupe,now());if(result.changes)emit(userId,'notification:changed',{});}
 function noticeMembers(groupId,title,href,dedupe,exclude){for(const m of all('SELECT userId FROM group_members WHERE groupId=?',groupId))if(m.userId!==exclude)notify(m.userId,'group',title,href,dedupe);}
 function event(posterId,u,owner=false){const p=get('SELECT * FROM posters WHERE id=?',posterId)||fail(404,'Event not found');if(p.universityId!==u.universityId)fail(403,'Events stay on your campus');if(owner&&p.ownerId!==u.id)fail(403,'Only the organiser can manage this event');if(!owner&&p.status!=='PUBLISHED')fail(404,'Event is no longer published');return p;}
 const defaultSettings=posterId=>({posterId,capacity:50,duration:60,enabled:0,lat:null,lng:null,clubId:null});
 const settings=posterId=>get('SELECT * FROM event_settings WHERE posterId=?',posterId)||defaultSettings(posterId);
 const eventHref=p=>`/${p.universityId}/posters/${p.slug}`;
 function eventView(p,u){const s=settings(p.id),counts=get("SELECT SUM(status='registered') registered,SUM(status='waitlisted') waitlisted,SUM(checkedAt IS NOT NULL AND status='registered') checkedIn FROM registrations WHERE posterId=?",p.id),registration=get('SELECT status,checkedAt FROM registrations WHERE posterId=? AND userId=?',p.id,u.id);return {settings:s,registered:counts.registered||0,waitlisted:counts.waitlisted||0,checkedIn:counts.checkedIn||0,registration:registration||null,owner:p.ownerId===u.id,isTest:!!JSON.parse(p.publicData||p.content).isTest,groupId:get("SELECT id FROM campus_groups WHERE sourceType='event' AND sourceId=?",p.id)?.id||null};}
 function ensureGroup(u,name,type='manual',sourceId=null){let g=sourceId&&get('SELECT * FROM campus_groups WHERE sourceType=? AND sourceId=?',type,sourceId);if(!g){const groupId=id();run('INSERT INTO campus_groups VALUES (?,?,?,?,?,?,?)',groupId,u.universityId,u.id,name,type,sourceId,now());g=get('SELECT * FROM campus_groups WHERE id=?',groupId);run('INSERT INTO group_members (groupId,userId,createdAt) VALUES (?,?,?)',g.id,u.id,now());}return g;}
 function promote(p){const s=settings(p.id);if(!s.enabled||p.status!=='PUBLISHED')return;const count=get("SELECT COUNT(*) n FROM registrations WHERE posterId=? AND status='registered'",p.id).n;const promoted=all("SELECT userId FROM registrations WHERE posterId=? AND status='waitlisted' ORDER BY seq LIMIT ?",p.id,Math.max(0,s.capacity-count));for(const r of promoted){run("UPDATE registrations SET status='registered' WHERE posterId=? AND userId=?",p.id,r.userId);const g=get("SELECT * FROM campus_groups WHERE sourceType='event' AND sourceId=?",p.id);if(g)run('INSERT OR IGNORE INTO group_members (groupId,userId,createdAt) VALUES (?,?,?)',g.id,r.userId,now());}return promoted;}
 function promotedNotices(p,rows=[]){for(const r of rows)notify(r.userId,'event','A place opened up — your booking is confirmed',eventHref(p),'promoted:'+p.id+':'+now());}
 function group(groupId,u){const g=get('SELECT g.* FROM campus_groups g JOIN group_members m ON m.groupId=g.id WHERE g.id=? AND m.userId=? AND g.universityId=?',groupId,u.id,u.universityId);return g||fail(404,'Group not found');}
 const online=userId=>[...sockets].some(ws=>ws.user?.id===userId&&ws.readyState===1&&validSocket(ws));
 function groupView(g,u){return {...g,members:all('SELECT u.id,u.name,u.username,u.avatarId FROM group_members m JOIN users u ON u.id=m.userId WHERE m.groupId=?',g.id),unread:get('SELECT COUNT(*) n FROM group_messages WHERE groupId=? AND authorId<>? AND seq>(SELECT readSeq FROM group_members WHERE groupId=? AND userId=?)',g.id,u.id,g.id,u.id).n};}
 const club=(clubId,u)=>clubDirectory(u.universityId).clubs.find(c=>c.id===clubId)||fail(404,'Club not found');
 function team(teamId,u){return get('SELECT * FROM teams WHERE id=? AND universityId=?',teamId,u.universityId)||fail(404,'Team not found');}
 function teamView(t,u){return {...t,owner:person(t.ownerId),members:all('SELECT u.id,u.name,u.username,u.avatarId FROM group_members m JOIN users u ON u.id=m.userId WHERE m.groupId=?',t.groupId),application:get('SELECT status FROM team_applications WHERE teamId=? AND userId=?',t.id,u.id)?.status||null,...(t.ownerId===u.id?{applications:all('SELECT a.status,u.id,u.name,u.username,u.avatarId FROM team_applications a JOIN users u ON u.id=a.userId WHERE a.teamId=?',t.id)}:{groupId:get('SELECT 1 FROM group_members WHERE groupId=? AND userId=?',t.groupId,u.id)?t.groupId:null})};}
 function recordGame(r,state){if(!state.finished||!r.guestId)return;run('INSERT OR IGNORE INTO game_results VALUES (?,?,?,?,?,?,?,?)',r.id,r.matchNumber,r.universityId,r.game,r.hostId,r.guestId,state.winner===0?r.hostId:state.winner===1?r.guestId:null,r.updatedAt);}
 for(const r of all("SELECT * FROM game_rooms WHERE status='finished' AND guestId IS NOT NULL"))recordGame(r,JSON.parse(r.state));
 function stats(userId,u){peer(userId,u);const results=all('SELECT roomId,matchNumber,game,hostId,guestId,winnerId,finishedAt FROM game_results WHERE (hostId=? OR guestId=?) AND universityId=? ORDER BY finishedAt DESC LIMIT 100',userId,userId,u.universityId),summary=get('SELECT COUNT(*) played,SUM(winnerId=?) wins,SUM(winnerId IS NULL) draws,SUM(winnerId IS NOT NULL AND winnerId<>?) losses FROM game_results WHERE (hostId=? OR guestId=?) AND universityId=?',userId,userId,userId,userId,u.universityId);return {summary:{played:summary.played,wins:summary.wins||0,draws:summary.draws||0,losses:summary.losses||0},results,badges:[...(summary.played>=1?['First match']:[]),...(summary.wins>=1?['First win']:[]),...(summary.played>=10?['Regular player']:[]),...(summary.wins>=10?['Ten wins']:[])]};}
 function localStart(p){if(!p.date)return null;const zone=campusDetails[p.universityId].timeZone,target=Date.parse(`${p.date}T${p.time||'00:00'}:00Z`);let value=target;for(let i=0;i<3;i++){const parts=Object.fromEntries(campusDateParts(value,zone).map(p=>[p.type,p.value]));const rendered=Date.parse(`${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}:${parts.second}Z`);value+=target-rendered;}return new Date(value).toISOString();}
 function schedule(u){const rows=all("SELECT DISTINCT p.* FROM posters p LEFT JOIN registrations r ON r.posterId=p.id AND r.userId=? AND r.status='registered' LEFT JOIN saved_posters s ON s.posterId=p.id AND s.userId=? WHERE p.status='PUBLISHED' AND p.universityId=? AND (r.userId IS NOT NULL OR s.userId IS NOT NULL OR p.ownerId=?) ORDER BY json_extract(p.publicData,'$.date') LIMIT 300",u.id,u.id,u.universityId,u.id).map(p=>{const v=posters.present(p,false,u.id),s=settings(p.id);return {...v,kind:'event',startsAt:localStart(v),duration:s.duration,confirmed:p.ownerId===u.id||!!get("SELECT 1 FROM registrations WHERE posterId=? AND userId=? AND status='registered'",p.id,u.id),href:eventHref(p)};});const screenings=all('SELECT DISTINCT s.* FROM screenings s LEFT JOIN screening_subscriptions m ON m.screeningId=s.id AND m.userId=? WHERE s.universityId=? AND s.cancelled=0 AND (s.hostId=? OR m.userId IS NOT NULL) ORDER BY s.startsAt LIMIT 100',u.id,u.universityId,u.id).map(s=>({...s,kind:'screening',confirmed:true,href:s.roomId?'/watch/'+s.roomId:'/community/screenings'}));const items=[...rows,...screenings].filter(x=>x.startsAt).sort((a,b)=>a.startsAt.localeCompare(b.startsAt));return items.map(x=>({...x,conflicts:!x.isTest&&x.confirmed?items.filter(y=>y.id!==x.id&&!y.isTest&&y.confirmed&&Date.parse(x.startsAt)<Date.parse(y.startsAt)+y.duration*60000&&Date.parse(y.startsAt)<Date.parse(x.startsAt)+x.duration*60000).map(y=>y.id):[]}));}
 function remind(){for(const p of all("SELECT p.* FROM posters p JOIN event_settings e ON e.posterId=p.id WHERE p.status='PUBLISHED' AND e.enabled=1 AND json_extract(p.publicData,'$.isTest') IS NOT 1")){const v=JSON.parse(p.publicData),start=localStart({...v,universityId:p.universityId});if(start&&Date.parse(start)>Date.now()&&Date.parse(start)<Date.now()+3600000)for(const r of all("SELECT userId FROM registrations WHERE posterId=? AND status='registered'",p.id))notify(r.userId,'reminder',v.title+' starts within an hour',eventHref(p),'reminder:event:'+p.id+':'+start);}for(const s of all('SELECT * FROM screenings WHERE cancelled=0 AND startsAt>? AND startsAt<?',now(),new Date(Date.now()+3600000).toISOString()))for(const r of all('SELECT userId FROM screening_subscriptions WHERE screeningId=?',s.id))notify(r.userId,'reminder',s.title+' starts within an hour',s.roomId?'/watch/'+s.roomId:'/community/screenings','reminder:screening:'+s.id);}
 function changedEvent(p,action){const v=JSON.parse(p.publicData||p.content),rows=all("SELECT userId FROM registrations WHERE posterId=? AND status<>'cancelled'",p.id);for(const r of rows)notify(r.userId,'event',action==='unpublish'?'An event you booked is no longer published':v.title+' has been updated',action==='unpublish'?'/community/calendar':eventHref(p),'event-change:'+p.id+':'+p.version);const s=settings(p.id);if(action==='publish'&&s.clubId){for(const f of all('SELECT userId FROM club_follows WHERE universityId=? AND clubId=?',p.universityId,s.clubId))if(f.userId!==p.ownerId)notify(f.userId,'club',v.title+' · a new community event',eventHref(p),'club-event:'+p.id+':'+p.version);}}
 async function handle(req,res,url){
  const parts=url.pathname.slice('/api/community/'.length).split('/').map(decodeURIComponent),method=req.method;let u=campusAccount(req);const input=['POST','PATCH','DELETE'].includes(method)?await body(req):{};u=campusAccount(req);
  if(parts[0]==='notifications'){
   if(method==='GET')return json(res,200,{notifications:all('SELECT id,kind,title,href,createdAt,readAt FROM notifications WHERE userId=? ORDER BY seq DESC LIMIT 100',u.id),unread:get('SELECT COUNT(*) n FROM notifications WHERE userId=? AND readAt IS NULL',u.id).n});
   if(method==='POST'){if(parts[1])run('UPDATE notifications SET readAt=? WHERE userId=? AND id=?',now(),u.id,parts[1]);else run('UPDATE notifications SET readAt=? WHERE userId=? AND readAt IS NULL',now(),u.id);emit(u.id);return json(res,200,{ok:true});}
  }
  if(parts[0]==='events'){
   const p=event(parts[1],u,parts[2]==='settings'||parts[2]==='guests'||parts[2]==='check-in'||parts[2]==='announce');
   if(method==='GET'&&!parts[2])return json(res,200,eventView(p,u));
   if(parts[2]==='settings'&&method==='PATCH'){
    const current=settings(p.id),s={...current,...input};if(Object.keys(input).some(k=>!['capacity','duration','enabled','lat','lng','clubId'].includes(k)))fail(400,'Unknown event setting');integer(s.capacity,1,500,'Capacity');integer(s.duration,15,720,'Duration');if(typeof s.enabled!=='boolean'&&s.enabled!==0&&s.enabled!==1)fail(400,'Choose whether registration is open');const content=JSON.parse(p.publicData||p.content);if(s.enabled&&(content.isTest||!person(p.ownerId)))fail(400,'Test notices cannot accept real bookings');if(s.lat!==null&&(typeof s.lat!=='number'||s.lat<-90||s.lat>90||!Number.isFinite(s.lat)))fail(400,'Invalid latitude');if(s.lng!==null&&(typeof s.lng!=='number'||s.lng<-180||s.lng>180||!Number.isFinite(s.lng)))fail(400,'Invalid longitude');if((s.lat===null)!==(s.lng===null))fail(400,'Set both map coordinates');if(s.clubId)club(s.clubId,u);if(s.capacity<get("SELECT COUNT(*) n FROM registrations WHERE posterId=? AND status='registered'",p.id).n)fail(409,'Capacity cannot be below confirmed bookings');let promoted;transaction(()=>{run('INSERT INTO event_settings VALUES (?,?,?,?,?,?,?) ON CONFLICT(posterId) DO UPDATE SET capacity=excluded.capacity,duration=excluded.duration,enabled=excluded.enabled,lat=excluded.lat,lng=excluded.lng,clubId=excluded.clubId',p.id,s.capacity,s.duration,Number(s.enabled),s.lat,s.lng,s.clubId||null);promoted=promote(p);});promotedNotices(p,promoted);changedEvent({...p,version:now()},'publish');return json(res,200,eventView(p,u));
   }
   if(parts[2]==='register'&&['POST','DELETE'].includes(method)){
    const content=JSON.parse(p.publicData);if(content.isTest||!person(p.ownerId))fail(400,'Test notices cannot accept real bookings');const s=settings(p.id);if(method==='POST'&&(!s.enabled||!content.date||Date.parse(localStart({...content,universityId:p.universityId}))+s.duration*60000<Date.now()))fail(409,'Registration is closed');let promoted=[];transaction(()=>{const old=get('SELECT * FROM registrations WHERE posterId=? AND userId=?',p.id,u.id);if(method==='DELETE'){run("UPDATE registrations SET status='cancelled',checkedAt=NULL WHERE posterId=? AND userId=?",p.id,u.id);const g=get("SELECT id FROM campus_groups WHERE sourceType='event' AND sourceId=?",p.id);if(g&&u.id!==p.ownerId)run('DELETE FROM group_members WHERE groupId=? AND userId=?',g.id,u.id);promoted=promote(p)||[];}else if(!old||old.status==='cancelled'){const count=get("SELECT COUNT(*) n FROM registrations WHERE posterId=? AND status='registered'",p.id).n,status=count<s.capacity?'registered':'waitlisted';run('INSERT INTO registrations (posterId,userId,status,ticket,createdAt) VALUES (?,?,?,?,?) ON CONFLICT(posterId,userId) DO UPDATE SET status=excluded.status,ticket=excluded.ticket,createdAt=excluded.createdAt,checkedAt=NULL,seq=(SELECT COALESCE(MAX(seq),0)+1 FROM registrations)',p.id,u.id,status,id(),now());if(status==='registered'){const g=ensureGroup({...u,id:p.ownerId},content.title,'event',p.id);run('INSERT OR IGNORE INTO group_members (groupId,userId,createdAt) VALUES (?,?,?)',g.id,u.id,now());}}});promotedNotices(p,promoted);emit(u.id);return json(res,200,eventView(p,u));
   }
   if(parts[2]==='ticket'&&method==='GET'){const r=get("SELECT ticket,status,checkedAt FROM registrations WHERE posterId=? AND userId=? AND status='registered'",p.id,u.id)||fail(404,'A confirmed booking is needed');const href='/community/organiser?event='+p.id+'&ticket='+r.ticket;return json(res,200,{...r,qr:await QRCode.toDataURL(href,{width:220,margin:2}),href});}
   if(parts[2]==='guests'&&method==='GET')return json(res,200,{guests:all('SELECT r.status,r.createdAt,r.checkedAt,u.id,u.name,u.username,u.avatarId FROM registrations r JOIN users u ON u.id=r.userId WHERE posterId=? ORDER BY r.seq',p.id),...eventView(p,u)});
   if(parts[2]==='check-in'&&method==='POST'){const ticket=text(input.ticket,36,'Ticket');const r=get("SELECT * FROM registrations WHERE posterId=? AND ticket=? AND status='registered'",p.id,ticket)||fail(404,'Valid confirmed ticket not found');run('UPDATE registrations SET checkedAt=COALESCE(checkedAt,?) WHERE posterId=? AND userId=?',now(),p.id,r.userId);return json(res,200,{person:person(r.userId),alreadyCheckedIn:!!r.checkedAt});}
   if(parts[2]==='announce'&&method==='POST'){const message=text(input.body,300,'Announcement');if(get("SELECT COUNT(*) n FROM notifications WHERE dedupe LIKE ? AND createdAt>?",'announcement:'+p.id+':%',new Date(Date.now()-60000).toISOString()).n)fail(429,'Wait one minute before another announcement');const dedupe='announcement:'+p.id+':'+id();for(const r of all("SELECT userId FROM registrations WHERE posterId=? AND status<>'cancelled'",p.id))notify(r.userId,'event',message,eventHref(p),dedupe);return json(res,200,{ok:true});}
  }
  if(parts[0]==='organiser'&&method==='GET'){return json(res,200,{events:all('SELECT * FROM posters WHERE ownerId=? AND universityId=? ORDER BY updatedAt DESC LIMIT 100',u.id,u.universityId).map(p=>({...posters.present(p,true,u.id),...eventView(p,u),views:get('SELECT COUNT(*) n FROM event_views WHERE posterId=?',p.id).n}))});}
  if(parts[0]==='friends'){
   if(method==='GET'){const rows=all('SELECT * FROM friends WHERE user1=? OR user2=?',u.id,u.id).map(f=>({...f,person:person(f.user1===u.id?f.user2:f.user1)})).filter(f=>f.person);return json(res,200,{friends:rows.map(f=>({...f,online:f.status==='accepted'&&online(f.person.id)}))});}
   const target=peer(parts[1],u);if(target.id===u.id)fail(400,'Choose another student');const pair=[u.id,target.id].sort(),f=get('SELECT * FROM friends WHERE user1=? AND user2=?',...pair);
   if(method==='POST'){if(!f){run("INSERT INTO friends VALUES (?,?,?,'pending',?)",...pair,u.id,now());notify(target.id,'friend',u.name+' sent you a friend request','/community/friends','friend:'+pair.join(':')+':'+now());}else if(f.status==='pending'&&f.requestedBy!==u.id){run("UPDATE friends SET status='accepted' WHERE user1=? AND user2=?",...pair);notify(target.id,'friend',u.name+' accepted your friend request','/community/friends','accepted:'+pair.join(':')+':'+now());}emit(u.id);emit(target.id);return json(res,200,{ok:true});}
   if(method==='DELETE'){run('DELETE FROM friends WHERE user1=? AND user2=?',...pair);emit(u.id);emit(target.id);return json(res,200,{ok:true});}
  }
  if(parts[0]==='groups'){
   if(!parts[1]){if(method==='GET')return json(res,200,{groups:all('SELECT g.* FROM campus_groups g JOIN group_members m ON m.groupId=g.id WHERE m.userId=? AND g.universityId=? ORDER BY g.createdAt DESC LIMIT 100',u.id,u.universityId).map(g=>groupView(g,u))});if(method==='POST'){const name=text(input.name,80,'Group name'),memberIds=input.memberIds;if(!Array.isArray(memberIds)||memberIds.length<1||memberIds.length>29||new Set(memberIds).size!==memberIds.length)fail(400,'Choose 1–29 different friends');for(const memberId of memberIds){peer(memberId,u);const pair=[u.id,memberId].sort();if(!get("SELECT 1 FROM friends WHERE user1=? AND user2=? AND status='accepted'",...pair))fail(403,'Only accepted friends can be added');}if(get("SELECT COUNT(*) n FROM campus_groups WHERE ownerId=? AND sourceType='manual'",u.id).n>=30)fail(429,'You already have 30 groups');const g=transaction(()=>{const g=ensureGroup(u,name);for(const memberId of memberIds)run('INSERT INTO group_members (groupId,userId,createdAt) VALUES (?,?,?)',g.id,memberId,now());return g;});noticeMembers(g.id,u.name+' added you to '+name,'/community/groups/'+g.id,'group-created:'+g.id,u.id);return json(res,201,{group:groupView(g,u)});}}
   const g=group(parts[1],u);
   if(method==='GET'&&!parts[2])return json(res,200,{group:groupView(g,u)});
   if(parts[2]==='messages'){
    const select='SELECT m.seq,m.id,m.authorId,m.body,m.createdAt,u.name author,u.username,u.avatarId FROM group_messages m JOIN users u ON u.id=m.authorId WHERE m.groupId=?';
    if(method==='GET'){const before=url.searchParams.get('before');if(before!==null&&(!/^\d+$/.test(before)||!Number.isSafeInteger(Number(before))))fail(400,'Invalid cursor');return json(res,200,{messages:all(select+' AND m.seq<? ORDER BY m.seq DESC LIMIT 50',g.id,before?Number(before):Number.MAX_SAFE_INTEGER).reverse()});}
    if(method==='POST'){const message=text(input.body,2000,'Message');if(typeof input.clientId!=='string'||!/^[a-f0-9-]{36}$/.test(input.clientId))fail(400,'Invalid message request');const old=get('SELECT * FROM group_messages WHERE authorId=? AND clientId=?',u.id,input.clientId);if(old){if(old.groupId!==g.id||old.body!==message)fail(409,'This request sent another message');return json(res,200,{ok:true});}if(get('SELECT COUNT(*) n FROM group_messages WHERE authorId=? AND createdAt>?',u.id,new Date(Date.now()-60000).toISOString()).n>=30)fail(429,'Wait a minute before more messages');run('INSERT INTO group_messages (id,groupId,authorId,clientId,body,createdAt) VALUES (?,?,?,?,?,?)',id(),g.id,u.id,input.clientId,message,now());for(const m of all('SELECT userId FROM group_members WHERE groupId=?',g.id))emit(m.userId,'group:changed',{groupId:g.id});noticeMembers(g.id,u.name+' · '+g.name,'/community/groups/'+g.id,'group-message:'+g.id+':'+input.clientId,u.id);return json(res,201,{ok:true});}
   }
   if(parts[2]==='read'&&method==='POST'){run('UPDATE group_members SET readSeq=(SELECT COALESCE(MAX(seq),0) FROM group_messages WHERE groupId=?) WHERE groupId=? AND userId=?',g.id,g.id,u.id);emit(u.id);return json(res,200,{ok:true});}
   if(parts[2]==='members'&&method==='DELETE'){const target=input.userId||u.id;if(g.ownerId!==u.id&&target!==u.id)fail(403,'Only the owner can remove members');if(target===g.ownerId)fail(409,'Transfer ownership before leaving');run('DELETE FROM group_members WHERE groupId=? AND userId=?',g.id,target);emit(target);return json(res,200,{ok:true});}
   if(parts[2]==='owner'&&method==='POST'){if(g.ownerId!==u.id)fail(403,'Only the owner can transfer ownership');if(!get('SELECT 1 FROM group_members WHERE groupId=? AND userId=?',g.id,input.userId))fail(400,'Choose a group member');run('UPDATE campus_groups SET ownerId=? WHERE id=?',input.userId,g.id);return json(res,200,{ok:true});}
  }
  if(parts[0]==='clubs'){
   if(!parts[1]&&method==='GET')return json(res,200,{following:all('SELECT clubId FROM club_follows WHERE universityId=? AND userId=?',u.universityId,u.id).map(f=>f.clubId)});
   const c=club(parts[1],u);
   if(!parts[2]&&method==='GET')return json(res,200,{club:c,following:!!get('SELECT 1 FROM club_follows WHERE universityId=? AND clubId=? AND userId=?',u.universityId,c.id,u.id),members:all('SELECT u.id,u.name,u.username,u.avatarId FROM club_follows f JOIN users u ON u.id=f.userId WHERE f.universityId=? AND f.clubId=? ORDER BY f.createdAt DESC LIMIT 50',u.universityId,c.id),memberCount:get('SELECT COUNT(*) n FROM club_follows WHERE universityId=? AND clubId=?',u.universityId,c.id).n,posts:all('SELECT p.id,p.body,p.createdAt,u.id authorId,u.name author,u.avatarId FROM club_posts p JOIN users u ON u.id=p.authorId WHERE p.universityId=? AND p.clubId=? ORDER BY p.createdAt DESC LIMIT 50',u.universityId,c.id),events:posters.list({join:"JOIN event_settings s ON s.posterId=p.id",where:"s.clubId=? AND p.universityId=? AND p.status='PUBLISHED'",params:[c.id,u.universityId],order:"p.publishedAt DESC LIMIT 30",viewerId:u.id})});
   if(parts[2]==='follow'&&['POST','DELETE'].includes(method)){if(method==='POST')run('INSERT OR IGNORE INTO club_follows VALUES (?,?,?,?)',u.universityId,c.id,u.id,now());else run('DELETE FROM club_follows WHERE universityId=? AND clubId=? AND userId=?',u.universityId,c.id,u.id);return json(res,200,{ok:true});}
   if(parts[2]==='posts'&&method==='POST'){if(!get('SELECT 1 FROM club_follows WHERE universityId=? AND clubId=? AND userId=?',u.universityId,c.id,u.id))fail(403,'Follow this community before posting');if(get('SELECT COUNT(*) n FROM club_posts WHERE authorId=? AND createdAt>?',u.id,new Date(Date.now()-60000).toISOString()).n>=5)fail(429,'Wait a minute before posting again');const postId=id();run('INSERT INTO club_posts VALUES (?,?,?,?,?,?)',postId,u.universityId,c.id,u.id,text(input.body,1000,'Post'),now());for(const f of all('SELECT userId FROM club_follows WHERE universityId=? AND clubId=?',u.universityId,c.id))if(f.userId!==u.id)notify(f.userId,'club',u.name+' posted in '+c.name,'/community/clubs/'+encodeURIComponent(c.id),'club-post:'+postId);return json(res,201,{ok:true});}
   if(parts[2]==='posts'&&method==='DELETE'){run('DELETE FROM club_posts WHERE id=? AND authorId=? AND universityId=? AND clubId=?',parts[3],u.id,u.universityId,c.id);return json(res,200,{ok:true});}

  }
  if(parts[0]==='feed'&&method==='GET')return json(res,200,{events:posters.list({join:"JOIN event_settings e ON e.posterId=p.id JOIN club_follows f ON f.clubId=e.clubId AND f.universityId=p.universityId",where:"f.userId=? AND p.universityId=? AND p.status='PUBLISHED'",params:[u.id,u.universityId],order:"p.publishedAt DESC LIMIT 100",viewerId:u.id})});
  if(parts[0]==='teams'){
   if(!parts[1]){if(method==='GET'){const q=string(url.searchParams.get('q')||'',60,'Search').toLowerCase(),category=url.searchParams.get('category')||'';return json(res,200,{teams:all('SELECT * FROM teams WHERE universityId=? AND (closed=0 OR ownerId=?) AND (?=\'\' OR category=?) AND instr(lower(title||\' \'||interests||\' \'||description),?)>0 ORDER BY createdAt DESC LIMIT 100',u.universityId,u.id,category,category,q).map(t=>teamView(t,u))});}if(method==='POST'){const title=text(input.title,100,'Team title'),description=text(input.description,1000,'Description'),interests=string(input.interests||'',120,'Interests'),category=input.category;if(!['Study','Sport','Project','Social'].includes(category))fail(400,'Choose a team type');const capacity=integer(input.capacity,2,30,'Team size'),startsAt=future(input.startsAt);if(get('SELECT COUNT(*) n FROM teams WHERE ownerId=? AND closed=0',u.id).n>=10)fail(429,'Close an existing team first');const t=transaction(()=>{const teamId=id(),g=ensureGroup(u,title,'team',teamId);run('INSERT INTO teams VALUES (?,?,?,?,?,?,?,?,?,0,?,?)',teamId,u.universityId,u.id,title,category,interests,description,startsAt,capacity,g.id,now());return team(teamId,u);});return json(res,201,{team:teamView(t,u)});}}
   const t=team(parts[1],u);
   if(!parts[2]&&method==='GET')return json(res,200,{team:teamView(t,u)});
   if(parts[2]==='apply'&&method==='POST'){if(t.closed||t.ownerId===u.id||Date.parse(t.startsAt)<Date.now())fail(409,'Applications are closed');const old=get('SELECT status FROM team_applications WHERE teamId=? AND userId=?',t.id,u.id);if(old?.status==='accepted')return json(res,200,{ok:true});run("INSERT INTO team_applications VALUES (?,?,'pending',?) ON CONFLICT(teamId,userId) DO UPDATE SET status='pending',createdAt=excluded.createdAt",t.id,u.id,now());notify(t.ownerId,'team',u.name+' applied to '+t.title,'/community/teams/'+t.id,'team-apply:'+t.id+':'+u.id+':'+now());return json(res,200,{ok:true});}
   if(parts[2]==='apply'&&method==='DELETE'){if(t.ownerId===u.id)fail(403,'The organiser cannot leave their own team');run("UPDATE team_applications SET status='cancelled' WHERE teamId=? AND userId=?",t.id,u.id);run('DELETE FROM group_members WHERE groupId=? AND userId=? AND userId<>?',t.groupId,u.id,t.ownerId);return json(res,200,{ok:true});}
   if(t.ownerId!==u.id)fail(403,'Only the team organiser can manage applications');
   if(parts[2]==='close'&&method==='POST'){run('UPDATE teams SET closed=1 WHERE id=?',t.id);return json(res,200,{ok:true});}
   if(parts[2]==='applications'&&method==='POST'){if(!['accepted','rejected'].includes(input.status))fail(400,'Accept or decline the application');const applicant=get('SELECT * FROM team_applications WHERE teamId=? AND userId=?',t.id,input.userId)||fail(404,'Application not found');if(applicant.status!=='pending')fail(409,'This application is no longer pending');transaction(()=>{if(input.status==='accepted'){if(t.closed||get('SELECT COUNT(*) n FROM group_members WHERE groupId=?',t.groupId).n>=t.capacity)fail(409,'This team is full or closed');run('INSERT OR IGNORE INTO group_members (groupId,userId,createdAt) VALUES (?,?,?)',t.groupId,applicant.userId,now());}run('UPDATE team_applications SET status=? WHERE teamId=? AND userId=?',input.status,t.id,applicant.userId);});notify(applicant.userId,'team',t.title+' · application '+input.status,'/community/teams/'+t.id,'team-result:'+t.id+':'+applicant.userId+':'+now());return json(res,200,{ok:true});}
  }
  if(parts[0]==='calendar'&&method==='GET'){const items=schedule(u);if(parts[1]==='export'){const eventCalendars=items.filter(x=>x.kind==='event').map(p=>calendarEvent(p,new URL(p.href,'https://'+req.headers.host).href));const blocks=[];const timezone=eventCalendars.map(c=>c.match(/BEGIN:VTIMEZONE[\s\S]*?END:VTIMEZONE/)?.[0]).find(Boolean);if(timezone)blocks.push(timezone);for(const c of eventCalendars)blocks.push(c.match(/BEGIN:VEVENT[\s\S]*?END:VEVENT/)[0]);for(const s of items.filter(x=>x.kind==='screening')){const stamp=value=>new Date(value).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');blocks.push(['BEGIN:VEVENT','UID:'+s.id+'@campuswall','DTSTAMP:'+stamp(now()),'DTSTART:'+stamp(s.startsAt),'DTEND:'+stamp(Date.parse(s.startsAt)+s.duration*60000),'SUMMARY:'+s.title.replace(/[\r\n;,\\]/g,' '),'END:VEVENT'].join('\r\n'));}res.writeHead(200,{'content-type':'text/calendar; charset=utf-8','cache-control':'no-store','content-disposition':'attachment; filename="campuswall-schedule.ics"'});return res.end(['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//CampusWall//My campus schedule//EN',...blocks,'END:VCALENDAR'].join('\r\n'));}return json(res,200,{items,timeZone:campusDetails[u.universityId].timeZone});}
  if(parts[0]==='map'&&method==='GET'){const notices=posters.list({where:"p.universityId=? AND p.status='PUBLISHED'",params:[u.universityId],order:"p.publishedAt DESC LIMIT 300",viewerId:u.id});const settingsById=new Map((notices.length?all(`SELECT * FROM event_settings WHERE posterId IN (${notices.map(()=>'?').join(',')})`,...notices.map(p=>p.id)):[]).map(s=>[s.posterId,s]));const events=notices.map(p=>({...p,...(settingsById.get(p.id)||defaultSettings(p.id)),href:eventHref(p)}));return json(res,200,{events});}
  if(parts[0]==='stats'&&method==='GET')return json(res,200,stats(parts[1]||u.id,u));
  if(parts[0]==='leaderboard'&&method==='GET'){const since=url.searchParams.get('period')==='all'?'1970-01-01T00:00:00.000Z':new Date(Date.now()-7*86400000).toISOString();return json(res,200,{leaders:all('SELECT u.id,u.name,u.username,u.avatarId,COUNT(*) played,SUM(r.winnerId=u.id) wins,SUM(r.winnerId IS NULL) draws FROM users u JOIN game_results r ON (r.hostId=u.id OR r.guestId=u.id) WHERE r.universityId=? AND r.finishedAt>=? GROUP BY u.id ORDER BY wins DESC,played DESC,u.name LIMIT 50',u.universityId,since)});}
  if(parts[0]==='screenings'){
   if(!parts[1]){if(method==='GET')return json(res,200,{screenings:all('SELECT s.*,EXISTS(SELECT 1 FROM screening_subscriptions m WHERE m.screeningId=s.id AND m.userId=?) subscribed FROM screenings s WHERE s.universityId=? AND s.cancelled=0 ORDER BY s.startsAt LIMIT 100',u.id,u.universityId).map(s=>({...s,host:person(s.hostId)}))});if(method==='POST'){const title=text(input.title,80,'Screening title'),startsAt=future(input.startsAt),duration=integer(input.duration,15,360,'Duration');let media;try{media=parseMedia(input.url);}catch(e){fail(400,e.message);}if(get('SELECT COUNT(*) n FROM screenings WHERE hostId=? AND cancelled=0 AND startsAt>?',u.id,now()).n>=10)fail(429,'You have ten scheduled screenings');const screeningId=id();run('INSERT INTO screenings (id,universityId,hostId,title,media,startsAt,duration,createdAt) VALUES (?,?,?,?,?,?,?,?)',screeningId,u.universityId,u.id,title,JSON.stringify(media),startsAt,duration,now());return json(res,201,{id:screeningId});}}
   const s=get('SELECT * FROM screenings WHERE id=? AND universityId=?',parts[1],u.universityId)||fail(404,'Screening not found');
   if(parts[2]==='subscribe'&&['POST','DELETE'].includes(method)){if(s.cancelled)fail(410,'This screening was cancelled');if(method==='POST')run('INSERT OR IGNORE INTO screening_subscriptions VALUES (?,?)',s.id,u.id);else run('DELETE FROM screening_subscriptions WHERE screeningId=? AND userId=?',s.id,u.id);return json(res,200,{ok:true});}
   if(s.hostId!==u.id)fail(403,'Only the host can manage this screening');
   if(parts[2]==='start'&&method==='POST'){if(s.cancelled)fail(410,'This screening was cancelled');if(s.roomId)return json(res,200,{roomId:s.roomId});if(get('SELECT COUNT(*) n FROM watch_rooms WHERE hostId=? AND closed=0',u.id).n>=5)fail(429,'Close an existing watch room first');const roomId=id();transaction(()=>{run('INSERT INTO watch_rooms (id,universityId,hostId,title,media,anchorAt,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?)',roomId,u.universityId,u.id,s.title,s.media,Date.now(),now(),now());run('UPDATE screenings SET roomId=? WHERE id=?',roomId,s.id);});watch.broadcast(watch.room(roomId));for(const m of all('SELECT userId FROM screening_subscriptions WHERE screeningId=?',s.id))notify(m.userId,'screening',s.title+' is ready to watch','/watch/'+roomId,'screening-start:'+s.id);return json(res,200,{roomId});}
   if(method==='DELETE'){run('UPDATE screenings SET cancelled=1 WHERE id=?',s.id);for(const m of all('SELECT userId FROM screening_subscriptions WHERE screeningId=?',s.id))notify(m.userId,'screening',s.title+' was cancelled','/community/calendar','screening-cancel:'+s.id);return json(res,200,{ok:true});}
  }
  if(parts[0]==='watch'){
   const r=watch.access(watch.room(parts[1]),u);
   if(!parts[2]&&method==='GET')return json(res,200,{inviteOnly:!!r.inviteOnly,invites:r.hostId===u.id?all('SELECT u.id,u.name,u.username FROM watch_invites i JOIN users u ON u.id=i.userId WHERE i.roomId=?',r.id):[],queue:all('SELECT q.id,q.title,q.authorId,COUNT(v.userId) votes,EXISTS(SELECT 1 FROM watch_votes x WHERE x.queueId=q.id AND x.userId=?) voted FROM watch_queue q LEFT JOIN watch_votes v ON v.queueId=q.id WHERE q.roomId=? AND q.playedAt IS NULL GROUP BY q.id ORDER BY votes DESC,q.createdAt LIMIT 30',u.id,r.id)});
   if(parts[2]==='queue'&&method==='POST'){let media;try{media=parseMedia(input.url);}catch(e){fail(400,e.message);}if(get('SELECT COUNT(*) n FROM watch_queue WHERE roomId=? AND playedAt IS NULL',r.id).n>=30)fail(429,'Playlist has 30 videos');run('INSERT INTO watch_queue VALUES (?,?,?,?,?,?,NULL)',id(),r.id,u.id,text(input.title,80,'Video title'),JSON.stringify(media),now());return json(res,201,{ok:true});}
   if(parts[2]==='vote'&&['POST','DELETE'].includes(method)){const q=get('SELECT id FROM watch_queue WHERE id=? AND roomId=? AND playedAt IS NULL',input.queueId,r.id)||fail(404,'Video not found');if(method==='POST')run('INSERT OR IGNORE INTO watch_votes VALUES (?,?)',q.id,u.id);else run('DELETE FROM watch_votes WHERE queueId=? AND userId=?',q.id,u.id);return json(res,200,{ok:true});}
   if(r.hostId!==u.id)fail(403,'Only the host can manage the room');if(input.version!==r.version)fail(409,'The room changed; try again');
   if(parts[2]==='privacy'&&method==='POST'){if(typeof input.inviteOnly!=='boolean')fail(400,'Choose room privacy');run('UPDATE watch_rooms SET inviteOnly=?,version=version+1 WHERE id=?',Number(input.inviteOnly),r.id);watch.broadcast(watch.room(r.id));return json(res,200,{ok:true});}
   if(parts[2]==='invite'&&method==='POST'){const p=peer(input.userId,u);run('INSERT OR IGNORE INTO watch_invites VALUES (?,?)',r.id,p.id);notify(p.id,'screening',u.name+' invited you to '+r.title,'/watch/'+r.id,'watch-invite:'+r.id+':'+p.id);return json(res,200,{ok:true});}
   if(parts[2]==='transfer'&&method==='POST'){const p=peer(input.userId,u);if(p.id===u.id||!watch.view(r).online.some(x=>x.id===p.id))fail(400,'Choose another online member');run('UPDATE watch_rooms SET hostId=?,version=version+1 WHERE id=?',p.id,r.id);run('INSERT OR IGNORE INTO watch_invites VALUES (?,?)',r.id,u.id);watch.broadcast(watch.room(r.id));notify(p.id,'screening','You are now hosting '+r.title,'/watch/'+r.id,'watch-transfer:'+r.id+':'+now());return json(res,200,{ok:true});}
   if(parts[2]==='next'&&method==='POST'){const q=get('SELECT q.*,COUNT(v.userId) votes FROM watch_queue q LEFT JOIN watch_votes v ON v.queueId=q.id WHERE q.roomId=? AND q.playedAt IS NULL GROUP BY q.id ORDER BY votes DESC,q.createdAt LIMIT 1',r.id)||fail(404,'Add a video to the playlist first');transaction(()=>{run('UPDATE watch_queue SET playedAt=? WHERE id=?',now(),q.id);run('UPDATE watch_rooms SET media=?,position=0,playing=0,buffering=0,anchorAt=?,version=version+1,updatedAt=? WHERE id=?',q.media,Date.now(),now(),r.id);});watch.broadcast(watch.room(r.id));return json(res,200,{ok:true});}
  }
  fail(405,'Community operation is not available');
 }
 function presenceChanged(userId){for(const f of all("SELECT user1,user2 FROM friends WHERE status='accepted' AND (user1=? OR user2=?)",userId,userId))emit(f.user1===userId?f.user2:f.user1,'friends:changed',{});}
 return {handle,notify,emit,recordGame,changedEvent,remind,stats,presenceChanged};
}
