import {parseMedia,playbackPosition} from './public/watch-model.js';
export function createWatch({db,get,all,run,id,now,fail,string,campusAccount,body,json,sockets,send,validSocket}){
 const room=id=>get('SELECT * FROM watch_rooms WHERE id=?',id)||fail(404,'Watch room not found');
 const person=userId=>get('SELECT id,name,username,avatarId FROM users WHERE id=?',userId);
 const select='SELECT m.seq,m.id,m.roomId,m.authorId,m.body,m.danmaku,m.position,m.createdAt,u.name author,u.username,u.avatarId FROM watch_messages m JOIN users u ON u.id=m.authorId';
 function access(r,u,closed=false){if(r.universityId!==u.universityId)fail(403,'Watch together on your own university');if(r.inviteOnly&&r.hostId!==u.id&&!get('SELECT 1 FROM watch_invites WHERE roomId=? AND userId=?',r.id,u.id))fail(404,'This watch room is invitation only');if(r.closed&&!closed)fail(410,'The host has closed this room');return r;}
 function online(r){const ids=new Set();for(const ws of sockets)if(ws.watchRoom===r.id&&ws.readyState===1&&validSocket(ws)&&ws.user.universityId===r.universityId)ids.add(ws.user.id);return [...ids].map(person);}
 function view(r){return {...r,media:JSON.parse(r.media),playing:!!r.playing,buffering:!!r.buffering,closed:!!r.closed,host:person(r.hostId),online:online(r),serverTime:Date.now()};}
 function list(u){return all('SELECT * FROM watch_rooms WHERE universityId=? AND closed=0 AND (inviteOnly=0 OR hostId=? OR EXISTS(SELECT 1 FROM watch_invites i WHERE i.roomId=watch_rooms.id AND i.userId=?)) ORDER BY updatedAt DESC LIMIT 40',u.universityId,u.id,u.id).map(r=>{const v=view(r);return {id:v.id,title:v.title,host:v.host,media:v.media,playing:v.playing,online:v.online,updatedAt:v.updatedAt};});}
 function history(r){return all(`${select} WHERE m.roomId=? ORDER BY m.seq DESC LIMIT 100`,r.id).reverse();}
 function broadcast(r,type='watch:state',data={}){let statePayload,lobbyPayload;for(const ws of sockets){if(ws.watchRoom===r.id){if(!validSocket(ws)){ws.close(4001,'Session expired');continue;}try{access(r,ws.user,true);send(ws,type,type==='watch:state'?(statePayload||={room:view(r)}):data);}catch{ws.close(4003,'Access ended');}}if(type==='watch:state'&&ws.watchLobby===r.universityId){if(validSocket(ws))send(ws,'watch:list',{rooms:list(ws.user)});else ws.close(4001,'Session expired');}}}
 function client(input){if(typeof input.clientId!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(input.clientId))fail(400,'Invalid watch request');}
 function media(value){try{return parseMedia(value);}catch(error){fail(400,error.message);}}
 function limit(u){if(get('SELECT COUNT(*) n FROM watch_requests WHERE userId=? AND createdAt>?',u.id,new Date(Date.now()-60000).toISOString()).n>=120)fail(429,'Please wait before sending more room controls');}
 async function handle(req,res,url){
  let u=campusAccount(req);const path=url.pathname,method=req.method;
  if(path==='/api/watch/rooms'){
   if(method==='GET')return json(res,200,{rooms:list(u)});
   if(method==='POST'){const input=await body(req);u=campusAccount(req);client(input);const title=string(input.title,80,'Room name');if(!title)fail(400,'Give your room a name');const source=media(input.url),payload=JSON.stringify({title,media:source});const previous=get('SELECT * FROM watch_requests WHERE userId=? AND clientId=?',u.id,input.clientId);if(previous){if(previous.operation!=='create'||previous.payload!==payload)fail(409,'This request already created another room');return json(res,200,{room:view(access(room(previous.roomId),u,true))});}limit(u);if(get('SELECT COUNT(*) n FROM watch_rooms WHERE hostId=? AND closed=0',u.id).n>=5)fail(429,'Close an existing room before creating another');const roomId=id(),time=now();db.exec('BEGIN');try{run('INSERT INTO watch_rooms (id,universityId,hostId,title,media,anchorAt,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?)',roomId,u.universityId,u.id,title,JSON.stringify(source),Date.now(),time,time);run('INSERT INTO watch_requests VALUES (?,?,?,?,?,?)',u.id,input.clientId,roomId,'create',payload,time);db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}const r=room(roomId);broadcast(r);return json(res,201,{room:view(r)});}
  }
  const match=path.match(/^\/api\/watch\/rooms\/([a-f0-9-]{36})(?:\/(control|messages))?$/);if(!match)fail(404,'Watch endpoint not found');let r=access(room(match[1]),u);const operation=match[2];
  if(method==='GET'){if(!operation)return json(res,200,{room:view(r)});if(operation==='messages')return json(res,200,{messages:history(r)});}
  if(method!=='POST'||!operation)fail(405,'Watch operation not available');const input=await body(req);u=campusAccount(req);r=access(room(r.id),u);client(input);
  if(operation==='messages'){const text=string(input.body,500,'Message');if(!text)fail(400,'Write a message first');if(input.danmaku!==undefined&&typeof input.danmaku!=='boolean')fail(400,'Choose whether to show this message on screen');const danmaku=input.danmaku!==false;const previous=get('SELECT * FROM watch_messages WHERE authorId=? AND clientId=?',u.id,input.clientId);if(previous){if(previous.roomId!==r.id||previous.body!==text||!!previous.danmaku!==danmaku)fail(409,'This request already sent another message');return json(res,200,{message:get(`${select} WHERE m.id=?`,previous.id)});}if(get('SELECT COUNT(*) n FROM watch_messages WHERE authorId=? AND createdAt>?',u.id,new Date(Date.now()-60000).toISOString()).n>=20)fail(429,'Please wait a minute before sending more messages');const messageId=id();run('INSERT INTO watch_messages (id,roomId,authorId,clientId,body,danmaku,position,createdAt) VALUES (?,?,?,?,?,?,?,?)',messageId,r.id,u.id,input.clientId,text,Number(danmaku),playbackPosition(r),now());const message=get(`${select} WHERE m.id=?`,messageId);broadcast(r,'watch:message',{message});return json(res,201,{message});}
  if(r.hostId!==u.id)fail(403,'Only the host controls this video');if(!['play','pause','seek','source','close','buffer'].includes(input.action))fail(400,'Choose a valid room control');
  if(input.action==='buffer'&&typeof input.buffering!=='boolean')fail(400,'Choose a valid buffering state');
  const source=input.action==='source'?media(input.url):null;let position=playbackPosition(r);if(['play','pause','seek','buffer'].includes(input.action)){if(typeof input.position!=='number'||!Number.isFinite(input.position)||input.position<0||input.position>604800)fail(400,'Choose a valid playback position');position=input.position;}
  const payload=JSON.stringify({action:input.action,position:['play','pause','seek','buffer'].includes(input.action)?position:null,media:source,...(input.action==='buffer'?{buffering:input.buffering}:{})});const previous=get('SELECT * FROM watch_requests WHERE userId=? AND clientId=?',u.id,input.clientId);if(previous){if(previous.roomId!==r.id||previous.operation!=='control'||previous.payload!==payload)fail(409,'This request already performed another control');return json(res,200,{room:view(r)});}
  limit(u);if(input.version!==r.version)fail(409,'The video changed. Sync again before controlling it');const time=now(),playing=input.action==='play'?1:input.action==='pause'||source||input.action==='close'?0:r.playing;
  db.exec('BEGIN');try{run('UPDATE watch_rooms SET media=?,position=?,playing=?,anchorAt=?,version=version+1,closed=?,buffering=?,updatedAt=? WHERE id=?',source?JSON.stringify(source):r.media,source?0:position,playing,Date.now(),Number(input.action==='close'),input.action==='buffer'?Number(input.buffering):['pause','source','close'].includes(input.action)?0:r.buffering,time,r.id);run('INSERT INTO watch_requests VALUES (?,?,?,?,?,?)',u.id,input.clientId,r.id,'control',payload,time);db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}r=room(r.id);broadcast(r);if(r.closed){for(const ws of sockets)if(ws.watchRoom===r.id){send(ws,'watch:closed',{});ws.close(4003,'Room closed');}}return json(res,200,{room:view(r)});
 }
 return {handle,room,access,view,list,history,broadcast,checkCapacity(r,u){const people=online(r);if(!people.some(p=>p.id===u.id)&&people.length>=50)fail(429,'This room has reached its 50-person limit');if([...sockets].filter(ws=>ws.watchRoom===r.id&&ws.user.id===u.id&&ws.readyState===1).length>=3)fail(429,'This room is already open in three of your tabs');}};
}
