BEGIN;
CREATE TABLE notifications (seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,userId TEXT NOT NULL REFERENCES users(id),kind TEXT NOT NULL,title TEXT NOT NULL,href TEXT NOT NULL,dedupe TEXT NOT NULL,createdAt TEXT NOT NULL,readAt TEXT,UNIQUE(userId,dedupe));
CREATE INDEX notifications_user ON notifications(userId,seq DESC);
CREATE TABLE event_settings (posterId TEXT PRIMARY KEY REFERENCES posters(id) ON DELETE CASCADE,capacity INTEGER NOT NULL DEFAULT 50,duration INTEGER NOT NULL DEFAULT 60,enabled INTEGER NOT NULL DEFAULT 0,lat REAL,lng REAL,clubId TEXT);
CREATE TABLE registrations (seq INTEGER PRIMARY KEY AUTOINCREMENT,posterId TEXT NOT NULL REFERENCES posters(id) ON DELETE CASCADE,userId TEXT NOT NULL REFERENCES users(id),status TEXT NOT NULL CHECK(status IN ('registered','waitlisted','cancelled')),ticket TEXT UNIQUE NOT NULL,createdAt TEXT NOT NULL,checkedAt TEXT,UNIQUE(posterId,userId));
CREATE INDEX registrations_event ON registrations(posterId,status,seq);
CREATE INDEX registrations_user ON registrations(userId,status);
CREATE TABLE event_views (posterId TEXT NOT NULL REFERENCES posters(id) ON DELETE CASCADE,visitor TEXT NOT NULL,day TEXT NOT NULL,PRIMARY KEY(posterId,visitor,day));
CREATE TABLE friends (user1 TEXT NOT NULL REFERENCES users(id),user2 TEXT NOT NULL REFERENCES users(id),requestedBy TEXT NOT NULL REFERENCES users(id),status TEXT NOT NULL CHECK(status IN ('pending','accepted')),createdAt TEXT NOT NULL,PRIMARY KEY(user1,user2),CHECK(user1<user2));
CREATE TABLE campus_groups (id TEXT PRIMARY KEY,universityId TEXT NOT NULL REFERENCES universities(id),ownerId TEXT NOT NULL REFERENCES users(id),name TEXT NOT NULL,sourceType TEXT NOT NULL DEFAULT 'manual',sourceId TEXT,createdAt TEXT NOT NULL,UNIQUE(sourceType,sourceId));
CREATE TABLE group_members (groupId TEXT NOT NULL REFERENCES campus_groups(id) ON DELETE CASCADE,userId TEXT NOT NULL REFERENCES users(id),readSeq INTEGER NOT NULL DEFAULT 0,createdAt TEXT NOT NULL,PRIMARY KEY(groupId,userId));
CREATE TABLE group_messages (seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,groupId TEXT NOT NULL REFERENCES campus_groups(id) ON DELETE CASCADE,authorId TEXT NOT NULL REFERENCES users(id),clientId TEXT NOT NULL,body TEXT NOT NULL,createdAt TEXT NOT NULL,UNIQUE(authorId,clientId));
CREATE INDEX group_messages_history ON group_messages(groupId,seq DESC);
CREATE INDEX group_messages_rate ON group_messages(authorId,createdAt);
CREATE TABLE club_follows (universityId TEXT NOT NULL REFERENCES universities(id),clubId TEXT NOT NULL,userId TEXT NOT NULL REFERENCES users(id),createdAt TEXT NOT NULL,PRIMARY KEY(universityId,clubId,userId));
CREATE TABLE club_posts (id TEXT PRIMARY KEY,universityId TEXT NOT NULL REFERENCES universities(id),clubId TEXT NOT NULL,authorId TEXT NOT NULL REFERENCES users(id),body TEXT NOT NULL,createdAt TEXT NOT NULL);
CREATE INDEX club_posts_campus ON club_posts(universityId,clubId,createdAt DESC);
CREATE TABLE teams (id TEXT PRIMARY KEY,universityId TEXT NOT NULL REFERENCES universities(id),ownerId TEXT NOT NULL REFERENCES users(id),title TEXT NOT NULL,category TEXT NOT NULL,interests TEXT NOT NULL,description TEXT NOT NULL,startsAt TEXT NOT NULL,capacity INTEGER NOT NULL,closed INTEGER NOT NULL DEFAULT 0,groupId TEXT NOT NULL REFERENCES campus_groups(id),createdAt TEXT NOT NULL);
CREATE INDEX teams_campus ON teams(universityId,closed,startsAt);
CREATE TABLE team_applications (teamId TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,userId TEXT NOT NULL REFERENCES users(id),status TEXT NOT NULL CHECK(status IN ('pending','accepted','rejected','cancelled')),createdAt TEXT NOT NULL,PRIMARY KEY(teamId,userId));
CREATE TABLE game_results (roomId TEXT NOT NULL REFERENCES game_rooms(id) ON DELETE CASCADE,matchNumber INTEGER NOT NULL,universityId TEXT NOT NULL REFERENCES universities(id),game TEXT NOT NULL,hostId TEXT NOT NULL REFERENCES users(id),guestId TEXT NOT NULL REFERENCES users(id),winnerId TEXT REFERENCES users(id),finishedAt TEXT NOT NULL,PRIMARY KEY(roomId,matchNumber));
CREATE INDEX game_results_campus ON game_results(universityId,finishedAt);
ALTER TABLE watch_rooms ADD COLUMN inviteOnly INTEGER NOT NULL DEFAULT 0;
CREATE TABLE watch_invites (roomId TEXT NOT NULL REFERENCES watch_rooms(id) ON DELETE CASCADE,userId TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(roomId,userId));
CREATE TABLE watch_queue (id TEXT PRIMARY KEY,roomId TEXT NOT NULL REFERENCES watch_rooms(id) ON DELETE CASCADE,authorId TEXT NOT NULL REFERENCES users(id),title TEXT NOT NULL,media TEXT NOT NULL,createdAt TEXT NOT NULL,playedAt TEXT);
CREATE INDEX watch_queue_room ON watch_queue(roomId,playedAt,createdAt);
CREATE TABLE watch_votes (queueId TEXT NOT NULL REFERENCES watch_queue(id) ON DELETE CASCADE,userId TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(queueId,userId));
CREATE TABLE screenings (id TEXT PRIMARY KEY,universityId TEXT NOT NULL REFERENCES universities(id),hostId TEXT NOT NULL REFERENCES users(id),title TEXT NOT NULL,media TEXT NOT NULL,startsAt TEXT NOT NULL,duration INTEGER NOT NULL DEFAULT 120,roomId TEXT REFERENCES watch_rooms(id),cancelled INTEGER NOT NULL DEFAULT 0,createdAt TEXT NOT NULL);
CREATE INDEX screenings_campus ON screenings(universityId,cancelled,startsAt);
CREATE TABLE screening_subscriptions (screeningId TEXT NOT NULL REFERENCES screenings(id) ON DELETE CASCADE,userId TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(screeningId,userId));
PRAGMA user_version=12;
COMMIT;
