import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Chess} from 'chess.js';
import {newGame,moveGame,publicGame,settleGame,reversiFlips} from '../game-engine.mjs';

test('gomoku connects five, respects turns, rejects occupied squares and retains immutable input',()=>{let s=newGame('gomoku');const initial=s;s=moveGame('gomoku',s,0,{index:0});assert.equal(initial.board[0],0);assert.throws(()=>moveGame('gomoku',s,0,{index:1}));assert.throws(()=>moveGame('gomoku',s,1,{index:0}));for(let i=1;i<5;i++){s=moveGame('gomoku',s,1,{index:210+i});s=moveGame('gomoku',s,0,{index:i});}assert.equal(s.winner,0);assert.equal(s.finished,true);assert.equal(s.winningCells.length,5);assert.throws(()=>moveGame('gomoku',s,1,{index:90}));});
test('connect four applies gravity, detects horizontal wins and prevents full-column moves',()=>{let s=newGame('connect4');for(let i=0;i<4;i++){s=moveGame('connect4',s,0,{column:i});if(i<3)s=moveGame('connect4',s,1,{column:6});}assert.equal(s.board[35],1);assert.equal(s.winner,0);s=newGame('connect4');for(let i=0;i<6;i++)s=moveGame('connect4',s,s.turn,{column:0});assert.throws(()=>moveGame('connect4',s,s.turn,{column:0}));assert.throws(()=>moveGame('connect4',s,s.turn,{column:7}));});
test('tic-tac-toe recognises a diagonal win and a full-board draw',()=>{let s=newGame('tictactoe');for(const index of [0,1,4,2,8])s=moveGame('tictactoe',s,s.turn,{index});assert.equal(s.winner,0);s=newGame('tictactoe');for(const index of [0,1,2,4,3,5,7,6,8])s=moveGame('tictactoe',s,s.turn,{index});assert.equal(s.finished,true);assert.equal(s.winner,null);});
test('rock paper scissors hides the first choice, handles ties and ends at two victories',()=>{let s=newGame('rps');s=moveGame('rps',s,0,{choice:0});const hidden=publicGame('rps',s,1);assert.equal(hidden.ownChoice,null);assert.deepEqual(hidden.chosen,[true,false]);assert.ok(!Object.hasOwn(hidden,'choices'));assert.throws(()=>moveGame('rps',s,0,{choice:2}));s=moveGame('rps',s,1,{choice:0});assert.deepEqual(s.scores,[0,0]);for(let i=0;i<2;i++){s=moveGame('rps',s,0,{choice:1});s=moveGame('rps',s,1,{choice:0});}assert.equal(s.finished,true);assert.equal(s.winner,0);});
test('memory hides every unseen card and changes turns only after the mismatch reveal interval',()=>{let s=newGame('memory',1000);assert.ok(publicGame('memory',s,0).cards.every(v=>v===null));const different=s.cards.findIndex(v=>v!==s.cards[0]);s=moveGame('memory',s,0,{index:0},1000);s=moveGame('memory',s,0,{index:different},1000);assert.equal(publicGame('memory',s,1).cards[0],s.cards[0]);assert.throws(()=>moveGame('memory',s,0,{index:1},1200));assert.equal(settleGame('memory',s,2599),false);assert.equal(settleGame('memory',s,2600),true);assert.equal(s.turn,1);assert.ok(publicGame('memory',s,0).cards.every(v=>v===null));});
test('memory rewards matching pairs, retains the turn and ends after all eight pairs',()=>{let s=newGame('memory');for(let value=0;value<8;value++){const pair=s.cards.flatMap((v,i)=>v===value?[i]:[]);for(const index of pair)s=moveGame('memory',s,0,{index});}assert.deepEqual(s.scores,[8,0]);assert.equal(s.winner,0);assert.equal(s.finished,true);});
const fleets=[{row:0,col:0,direction:'horizontal'},{row:2,col:0,direction:'horizontal'},{row:4,col:0,direction:'horizontal'}];
test('battleship validates complete fleets, rejects overlap and hides opponent ships until the match ends',()=>{let s=newGame('battleship');assert.throws(()=>moveGame('battleship',s,0,{type:'fleet',ships:[...fleets.slice(0,2),{row:0,col:1,direction:'horizontal'}]}));assert.throws(()=>moveGame('battleship',s,0,{type:'fleet',ships:[{row:7,col:7,direction:'vertical'},...fleets.slice(1)]}));s=moveGame('battleship',s,0,{type:'fleet',ships:fleets});s=moveGame('battleship',s,1,{type:'fleet',ships:fleets});assert.equal(s.phase,'battle');assert.equal(publicGame('battleship',s,0).opponentFleet,null);assert.ok(!Object.hasOwn(publicGame('battleship',s,0),'fleets'));for(const [n,index] of [0,1,2,3,16,17,18,32,33].entries()){s=moveGame('battleship',s,0,{index});if(n<8)s=moveGame('battleship',s,1,{index:48+n});}assert.equal(s.finished,true);assert.equal(s.winner,0);assert.equal(publicGame('battleship',s,0).opponentFleet.length,9);});
test('battleship rejects repeat shots and does not allow shooting before placement completes',()=>{let s=newGame('battleship');assert.throws(()=>moveGame('battleship',s,0,{index:0}));for(let p=0;p<2;p++)s=moveGame('battleship',s,p,{type:'fleet',ships:fleets});s=moveGame('battleship',s,0,{index:63});s=moveGame('battleship',s,1,{index:63});assert.throws(()=>moveGame('battleship',s,0,{index:63}));});
test('reversi requires a capture, flips discs, automatically passes and finishes when neither side can move',()=>{let s=newGame('reversi');assert.throws(()=>moveGame('reversi',s,0,{index:0}));assert.equal(reversiFlips(s.board,19,0).length,1);s=moveGame('reversi',s,0,{index:19});assert.equal(s.board[27],1);s=newGame('reversi');s.board=Array(64).fill(1);s.board[0]=s.board[7]=0;s.board[1]=s.board[6]=2;s=moveGame('reversi',s,0,{index:0});assert.equal(s.turn,0);assert.match(s.notice,/no legal move/);s=moveGame('reversi',s,0,{index:7});assert.equal(s.finished,true);assert.equal(s.winner,0);assert.deepEqual(s.scores,[64,0]);});
test('a complete legal reversi game terminates with a correctly counted winner',()=>{let s=newGame('reversi');for(let n=0;n<65&&!s.finished;n++){const legal=publicGame('reversi',s,s.turn).legal;assert.ok(legal.length);s=moveGame('reversi',s,s.turn,{index:legal[0]});}assert.equal(s.finished,true);const scores=[s.board.filter(v=>v===1).length,s.board.filter(v=>v===2).length];assert.deepEqual(s.scores,scores);assert.equal(s.winner,scores[0]===scores[1]?null:scores[0]>scores[1]?0:1);});
function chessMoves(moves){let s=newGame('chess');for(const [from,to] of moves)s=moveGame('chess',s,s.turn,{from,to});return s;}
test('chess validates moves and recognises checkmate',()=>{assert.throws(()=>moveGame('chess',newGame('chess'),0,{from:'e2',to:'e5'}));const s=chessMoves([['f2','f3'],['e7','e5'],['g2','g4'],['d8','h4']]);assert.equal(s.finished,true);assert.equal(s.winner,1);assert.match(s.notice,/Checkmate/);});
test('chess implements castling and en passant',()=>{let s=chessMoves([['e2','e4'],['e7','e5'],['g1','f3'],['b8','c6'],['f1','c4'],['f8','c5'],['e1','g1']]);assert.equal(new Chess(s.fen).get('f1').type,'r');assert.equal(new Chess(s.fen).get('g1').type,'k');s=chessMoves([['e2','e4'],['a7','a6'],['e4','e5'],['d7','d5'],['e5','d6']]);assert.equal(new Chess(s.fen).get('d5'),undefined);assert.equal(new Chess(s.fen).get('d6').color,'w');});
test('chess supports underpromotion and detects threefold repetition from persistent history',()=>{let s=newGame('chess');const c=new Chess('7k/P7/8/8/8/8/8/7K w - - 0 1');s.pgn=c.pgn();s.fen=c.fen();s=moveGame('chess',s,0,{from:'a7',to:'a8',promotion:'n'});assert.equal(new Chess(s.fen).get('a8').type,'n');s=chessMoves(Array.from({length:2},()=>[['g1','f3'],['g8','f6'],['f3','g1'],['f6','g8']]).flat());assert.equal(s.finished,true);assert.equal(s.winner,null);});
test('drawing exposes the word only to the artist, validates ink, accepts English synonyms with case and punctuation and swaps roles',()=>{let s=newGame('draw',1000);s.wordList[0]=['bicycle','bike'];assert.equal(publicGame('draw',s,1).word,null);assert.equal(publicGame('draw',s,0).word,'bicycle');assert.ok(!Object.hasOwn(publicGame('draw',s,1),'wordList'));assert.throws(()=>moveGame('draw',s,1,{type:'stroke',points:[[0,0],[.5,.5]],colour:'#001b44',width:5},1001));assert.throws(()=>moveGame('draw',s,0,{type:'stroke',points:[[2,0],[.5,.5]],colour:'#001b44',width:5},1001));s=moveGame('draw',s,0,{type:'stroke',points:[[0,0],[.5,.5]],colour:'#001b44',width:5},1001);assert.equal(publicGame('draw',s,1).strokes.length,1);s=moveGame('draw',s,1,{type:'guess',word:'Bike!'},1002);assert.equal(s.result.correct,true);assert.deepEqual(s.scores,[1,1]);settleGame('draw',s,3402);assert.equal(s.artist,1);assert.equal(s.round,1);assert.equal(s.strokes.length,0);assert.equal(publicGame('draw',s,0).word,null);});
test('drawing deadlines expire without guesses and complete all four cooperative rounds',()=>{const s=newGame('draw',1000);let time=1000;for(let i=0;i<4;i++){time+=60000;assert.equal(settleGame('draw',s,time),true);assert.equal(s.result.correct,false);time+=2400;settleGame('draw',s,time);}assert.equal(s.finished,true);assert.match(s.notice,/0 of 4/);});
test('quiz hides answers until both choose, rewards speed only for correct answers and rejects duplicates',()=>{let s=newGame('quiz',1000);s.questions[0]=['Question',['A','B','C','D'],2];s=moveGame('quiz',s,0,{choice:2},2000);const other=publicGame('quiz',s,1);assert.equal(other.ownAnswer,null);assert.equal(other.result,null);assert.ok(!Object.hasOwn(other,'questions'));assert.throws(()=>moveGame('quiz',s,0,{choice:1},2001));s=moveGame('quiz',s,1,{choice:0},4000);assert.equal(s.result.correct,2);assert.ok(s.scores[0]>100);assert.equal(s.scores[1],0);settleGame('quiz',s,6600);assert.equal(s.round,1);assert.deepEqual(s.answers,[null,null]);});
test('quiz timeouts score answered questions and end after eight rounds',()=>{let s=newGame('quiz',1000),time=1000;for(let i=0;i<8;i++){s=moveGame('quiz',s,0,{choice:s.questions[i][2]},time+1000);time+=20000;settleGame('quiz',s,time);assert.equal(s.result.answers[1],null);time+=2600;settleGame('quiz',s,time);}assert.equal(s.finished,true);assert.equal(s.winner,0);assert.ok(s.scores[0]>=800);});
